### ISSUE TITLE
dimensionality_reduction with isaggregation=True will throw an error 

### ISSUE THREAD

**Issue by dylan-baker** [TheJacksonLaboratory/scanpy_recipes#8]
adata just needs to be changed to data_filt

44     if is_aggregation:
---> 45         n_batches = len(adata.obs["batch"].unique())
     46         bbknn(
     47             adata_filt,

NameError: name 'adata' is not defined

**Comment by wflynny** [comment]
Fixed in e7ae5da86a7790c9ec3c7ff9c4a8464a655594fd.

For it to take effect, you'll have to `git pull && pip install -e .` again.
